/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/tree/main/packages/reactivity-transform#refs-vs-reactive
export {}

declare module 'vue' {
  export interface GlobalComponents {
    // Gamification Components
    ChallengeCard: typeof import('./components/ChallengeCard.vue')['default']
    LeaderboardEntry: typeof import('./components/LeaderboardEntry.vue')['default']
    PointsBadge: typeof import('./components/PointsBadge.vue')['default']
    ProgressRing: typeof import('./components/ProgressRing.vue')['default']
    StreakBadge: typeof import('./components/StreakBadge.vue')['default']
    
    // Existing LMS Components
    AssignmentCard: typeof import('./components/AssignmentCard.vue')['default']
    BatchCard: typeof import('./components/BatchCard.vue')['default']
    CourseCard: typeof import('./components/CourseCard.vue')['default']
    CourseProgressSummary: typeof import('./components/CourseProgressSummary.vue')['default']
    CourseReviews: typeof import('./components/CourseReviews.vue')['default']
    Evaluators: typeof import('./components/Evaluators.vue')['default']
    FileUploader: typeof import('./components/FileUploader.vue')['default']
    JobCard: typeof import('./components/JobCard.vue')['default']
    LessonCard: typeof import('./components/LessonCard.vue')['default']
    MobileLayout: typeof import('./components/MobileLayout.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    QuizBlock: typeof import('./components/QuizBlock.vue')['default']
    Settings: typeof import('./components/Settings.vue')['default']
    UserDropdown: typeof import('./components/UserDropdown.vue')['default']
    VideoStatistics: typeof import('./components/VideoStatistics.vue')['default']
  }
}